version: '3.9'

x-backend: &default-backend
  build: './backend'
  depends_on:
    - local-mongodb
    - custom-nginx
  networks:
    - my_network
  ports:
    - '5000:5000'
  volumes:
    - ./root:/tmp/root
  environment:
    - PORT=${PORT}
    - SECRET_KEY=${SECRET_KEY}
    - SALT_ROUNDS=${SALT_ROUNDS}
    - WEB_SERVER_RESOURCE_PATH=${WEB_SERVER_RESOURCE_PATH}
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}

services:
  custom-nginx:
    build: './custom-nginx'
    restart: always
    networks:
      - my_network
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./drive:/tmp/drive
      - ./root:/tmp/root

  local-mongodb:
    depends_on:
      - custom-nginx
    image: mongo
    networks:
      - my_network
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  web-file-system:
    depends_on:
      - custom-nginx
      - local-mongodb
      - backend-1
    build: './file-system-react'
    restart: always
    ports:
      - '3000:80'
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  backend-1:
    <<: *default-backend
    restart: always
    ports:
      - '5000:5000'

  # backend-2:
  #   <<: *default-backend
  #   ports:
  #     - '5001:5000'

networks:
  my_network:
    driver: bridge
